service: my-budget-buddy
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  stage: dev
  timeout: 10
  memorySize: 256
  runtime: nodejs20.x
  architecture: arm64
  logRetentionInDays: 60
  region: eu-central-1

custom:
  minification:
    dev: false
    prod: true
  esbuild:
    packager: npm
    bundle: true
    minify: ${self:custom.minification.${self:provider.stage}}
    target: node20
    keepOutputDirectory: true
    external:
      - '@aws-sdk'

functions:
  MyBudgetBuddyTelegramBot:
    handler: src/handlers/tg-bot.handler
    name: my-budget-buddy-tg-bot
    url: true
    environment:
      TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
      FORM_URL: ${env:FORM_URL}
      ALLOWED_USERS: ${env:ALLOWED_USERS}
    events:
      - schedule:
          name: my-budget-buddy-tg-bot-warmer-schedule
          rate: rate(5 minutes)
          enabled: false
          input:
            warmer: true

plugins:
  - serverless-esbuild
